### ISSUE TITLE
Transparency doesn't work in Lubuntu 20.04 running LXQT

### ISSUE THREAD

**Issue by hichemfantar** [SnosMe/electron-overlay-window#11]
The line "app.disableHardwareAcceleration()" doesn't fix the transparency issue for me on Lubuntu 20.04 which uses LXQT.
I get a black opaque background.

**Comment by SnosMe** [comment]
By creating issue here you mean that:
creating a transparent window with **regular electron API works**, only when creating a window with this library it's not transparent, correct?

Check that you didn't forget to add delay.

https://github.com/SnosMe/electron-overlay-window/blob/d75bf6137c99123d0d46715b336c3c0744603ff0/src/demo/electron-demo.ts#L33-L36
