### ISSUE TITLE
Is it possible to create an overlay in the whole screen?

### ISSUE THREAD

**Issue by biel-correa** [SnosMe/electron-overlay-window#18]
I was thinking on a project but in order to make it look great I need this feature. Will this lib provide it and can someone give any tip on how to do it?

**Comment by SnosMe** [comment]
You don't need this library to cover the whole screen.

**Comment by biel-correa** [comment]
Could you tell me what can I use?

**Comment by SnosMe** [comment]
It depends on what you want, but basically transparent frameless window

https://github.com/SnosMe/electron-overlay-window/blob/e0b3da27a20251cb5673c43390abdc2e3fe3e78e/src/index.ts#L62-L67

**Comment by biel-correa** [comment]
Thanks, you just saved me
