### ISSUE TITLE
Is there a way to detected when attached program end ?

### ISSUE THREAD

**Issue by BThiebaut** [SnosMe/electron-overlay-window#21]
Currently if the attached program being closed, the overlay process sill visible in task manager.
I want to be able to call app.quit(); when the attached program is ended, is there a way to do it ?

**Comment by SnosMe** [comment]
Yes  

https://github.com/SnosMe/electron-overlay-window/blob/e0b3da27a20251cb5673c43390abdc2e3fe3e78e/src/index.ts#L52
