### ISSUE TITLE
Please add a proper detach to the overlay window class as well

### ISSUE THREAD

**Issue by OSjoerdWie** [SnosMe/electron-overlay-window#3]
My target application doesn't seem to shutdown properly (Excel workbook on Windows 10). I suppose proper detaching could prevent this?

**Comment by SnosMe** [comment]
So how Excel shutdowns now?

**Comment by OSjoerdWie** [comment]
Apologies; I just realized that it seems like something that I changed at the same time as including your library - but forgot about - seems to have caused the issue. As it seems, the overlay had nothing to do with it.

**Comment by somanuell** [comment]
> [...}

Hi SjoerD, could you have a look at https://github.com/durs/node-activex/issues/103 please.

Apology to Alexander for hijacking the issue, I don't know how to contact a dev here
