### ISSUE TITLE
Error When Using electron-overlay-window

### ISSUE THREAD

**Issue by mcread29** [SnosMe/electron-overlay-window#32]
![image](https://user-images.githubusercontent.com/19232189/213364639-ae322c32-60a8-41a0-ad57-2b3a071e309f.png)
I keep getting this error when trying to use anything from the package, even if it's just the const OVERLAY_WINDOW_OPTS. I don't know if it's a webpack issue or if it's something with the package itself. 

![image](https://user-images.githubusercontent.com/19232189/213365483-ec1294f3-6b89-49fe-9632-96b9890374bf.png)
Doing this causes the error

![image](https://user-images.githubusercontent.com/19232189/213365530-5840e527-9e95-4dc5-bb39-f4e18b2d1ad2.png)
but this runs without issue.

This is using Windows 10

Any help or advice would be appreciated

EDIT: 
Cloning the source repo and running `yarn demo:electron` does seem to work as intended, but importing it into an existing project is causing the issue.

**Comment by SnosMe** [comment]
Visit similar issue with webpack in my another repo https://github.com/SnosMe/uiohook-napi/issues/28
Yes, you need to properly configure webpack
