### ISSUE TITLE
app not working when use win.setIgnoreMouseEvents(true) and overlayWindow 

### ISSUE THREAD

**Issue by pmqueiroz** [SnosMe/electron-overlay-window#4]
I'm developing an overlay app with a friend and when I coded in my computer all seems to be working properly, although the application was appearing on the screen and staying on top of others apps, on my friend's computer nothing is showing in the screen and the console are being normal. Is that a bug on your module?

How do we made the app appear
```js
app.on('ready', () => {
    createOverlay()
})

const createOverlay = () => {
    win = new BrowserWindow({ 
        ...overlayWindow.WINDOW_OPTS,
        alwaysOnTop: true, 
        y: 0, 
        x: 0,
        frame: false
    })

    win.setIgnoreMouseEvents(true)

    //a bunch of code here
}
```

the source code of this project [here](https://github.com/MatheusSESH/twitch-chat-overlay)

EDIT: spellcheck

**Comment by SnosMe** [comment]
You should read about Windows UIPI

And here's how to check it. Also please don't use `alwaysOnTop` (I've not checked if it compatible with it, but electron-overlay-window was intentionally developed in a way to dont use it)

https://github.com/SnosMe/electron-overlay-window/blob/7fa3cb49413402102d56907fb43288598ce41623/src/index.ts#L49

https://github.com/SnosMe/electron-overlay-window/blob/7fa3cb49413402102d56907fb43288598ce41623/src/index.ts#L29

**Comment by pmqueiroz** [comment]
yeah, that's work but the app isn't overlaying the apps without stay on top

**Comment by SnosMe** [comment]
https://github.com/SnosMe/electron-overlay-window/blob/master/src/demo/electron-demo.ts
