### ISSUE TITLE
Add a Documentation

### ISSUE THREAD

**Issue by xRealNeon** [SnosMe/electron-overlay-window#5]
Can you add a documentation I don't know how to use this

**Comment by SnosMe** [comment]
Documentation is 

https://github.com/SnosMe/electron-overlay-window/blob/master/src/demo/electron-demo.ts
and
https://github.com/SnosMe/electron-overlay-window/blob/master/src/index.ts

I don't think it's hard to read just two files (205 LOC).
This library is part of another project.

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND
