### ISSUE TITLE
How do I detach a window

### ISSUE THREAD

**Issue by Taimoor-Tariq** [SnosMe/electron-overlay-window#6]
I tried closing the window I attached to my program so I can attach a new window on it, but it still has that non existing window attached to it.

Also is there a way to toggle the visibility of the overlay window?

**Comment by SnosMe** [comment]
1. If you want to close overlay window, you need to close the electron app all together.
2. Use CSS

**Comment by Taimoor-Tariq** [comment]
I can use CSS as I'm using `ingameOverlay.loadURL('link to URL');` to load the window.

Usually I would use `ingameOverlay.hide()` or `ingameOverlay.show()` to hide or show the windows but doing that does not work when I attach it to my game application.

I tried using `ingameOverlay.setSize(0,0)` and it worked but i need to know the size of the target app to resize it back to normal (show on screen)

**Comment by SnosMe** [comment]
I think you have to revisit docs, you are controlling browser and can do whatever you want.

https://www.electronjs.org/docs/api/web-contents#contentsexecutejavascriptcode-usergesture

**Comment by Taimoor-Tariq** [comment]
Thanks
