### ISSUE TITLE
Question regarding detaching

### ISSUE THREAD

**Issue by pl4yradam** [SnosMe/electron-overlay-window#8]
Hi there,  

I have implemented the package to run, but I see some strange behaviour. I see the docs say you can only run the overlay for 1 Window per LIVE electron main process?

Why can't you remove the overlay without ending your whole electron app?

To resolve:
Do you suggest compiling an 'overlay.exe' that another electron overlay uses? It seems strange that the only solution is top stop your app.

**Comment by SnosMe** [comment]
This library was developed for another project, so there was no reason to implement such functionality. Proper lifecycle cleanup and state instances should be created to support this.

Currently, it intended to work with one window that has a stable non-changing title, if you need to hide overlay use CSS.

**Comment by pl4yradam** [comment]
Yep, I can see that it has been developed for a specific use case, info for anyone in the future reading:

https://github.com/SnosMe/electron-overlay-window/blob/master/src/lib/addon.c#L198
 - You can see here cleanup hasn't been done, hence the only way to clean this up is to stop the app, Cleaning up and being able to relaunch would completely enable this package.
 - Depending on the windowed mode of the application, the overlay may or may not work, experimenting with multiple games in different windowed states, borderless, windowed, fullscreen.
