### ISSUE TITLE
Overlay window is not transparent on Linux

### ISSUE THREAD

**Issue by TheGreatMcPain** [SnosMe/electron-overlay-window#9]
When I tried the demo code on a file manager window `pcmanfm` the overlay did not go transparent.

The window manager I use is bspwm and the compositor is picom (fork of compton).

**Comment by TheGreatMcPain** [comment]
Apparently it's related to [electron issue #25153](https://github.com/electron/electron/issues/25153).

**Comment by SnosMe** [comment]
https://github.com/SnosMe/electron-overlay-window/commit/d75bf6137c99123d0d46715b336c3c0744603ff0
